//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ReviewContent { get; set; }
        public int Rating { get; set; }
        public int Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
